(load "tokens")

(defparameter *oldsym* ())
(defparameter *sym* ())
(defparameter *symbol-table* ())
(defparameter *depth* 0)
(defparameter *accept* T)

;;; Convenience function so popping from symbol table fails gracefully.
(defun table-pop (symbol-table)
  (if (> (fill-pointer symbol-table) 0)
    (vector-pop symbol-table)))

(defun get-sym ()
  (defparameter *oldsym* *sym*)
  (setf *sym* (table-pop *symbol-table*))
  (if (null *sym*)
    (setf *sym* (cons 'eof T))))

(defun unget-sym ()
  (format T "Ungetting ~S.. " *sym*)
  (vector-push-extend *sym* *symbol-table*)
  (defparameter *sym* *oldsym*)
  (format T "sym now ~S~%" *sym*)
  )

(defun parse-err (str)
  (format T "~,,v,@A" (* *depth* 2) (format NIL "[ERROR ~S] ~@?" *depth* str))
  (setf *accept* NIL)
  )

(defun parse-info (str)
  (format T "~,,v,@A" (* 2 *depth*) (format NIL "[INFO ~S] ~@?" *depth* str))
  )

(defun accept (token-type)
  (parse-info (format NIL "Parsing ~S on ~S.. " token-type *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((equal (car *sym*) token-type)
           (format T "accepted~%")
           (get-sym)
           T)
          (T
            (format T "rejected~%")
            NIL)))
  )

(defun expect (token-type)
  (cond ((accept token-type) T)
        (T
          (parse-err (format NIL "Expected ~S, got ~S instead~%" token-type (car *sym*))) NIL)))

(defun parse (symbol-table)
  (setf *symbol-table* symbol-table)
  (get-sym)
  (parse-S)
  (and *accept* (equal (car *sym*) 'eof)))

(defun parse-S ()
  (parse-info (format NIL "Parsing S on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'leftp-dt)
           (parse-S)
           (expect 'rightp-dt)
           (parse-S))
          ((parse-expr)
           (parse-S))
          ((accept 'eof))
          (T
            (parse-info "Attempted all derivations, assuming empty string~%")
            T)))
  )

(defun parse-expr ()
  (parse-info (format NIL "Parsing expr on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((parse-oper))
          ((parse-stmt))
          (T (parse-info "Unable to parse expr~%") NIL)))
  )

(defun parse-oper ()
  (parse-info (format NIL "Parsing oper on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'leftp-dt)
           (parse-Poper)
           (expect 'rightp-dt))
          ((parse-const))
          ((parse-id))
          (T (parse-info "Unable to parse oper~%") NIL)))
  )

(defun parse-Poper ()
  (parse-info (format NIL "Parsing Poper on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'assign-st)
           (parse-id)
           (parse-oper))
          ((accept 'binop-ot)
           (parse-oper)
           (parse-oper))
          ((accept 'unop-ot)
           (parse-oper))
          (T (parse-info "Unable to parse Poper~%") NIL)))
  )

(defun parse-stmt ()
  (parse-info (format NIL "Parsing stmt on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'leftp-dt)
           (parse-Pstmt)
           (expect 'rightp-dt))
          (T (parse-info "Unable to parse stmt~%") NIL)))
  )

(defun parse-Pstmt ()
  (parse-info (format NIL "Parsing Pstmt on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((parse-ifstmt))
          ((parse-elifstmt))
          ((accept 'while-st)
           (parse-expr)
           (parse-exprs))
          ((accept 'let-st)
           (expect 'leftp-dt)
           (parse-ids)
           (expect 'rightp-dt))
          ((accept 'stdout-st)
           (parse-oper))
          (T (parse-info "Unable to parse Pstmt~%") NIL)))
  )

(defun parse-ifstmt ()
  (parse-info (format NIL "Parsing ifstmt on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'if-st)
           (parse-expr)
           (parse-expr))
          (T (parse-info "Unable to parse ifstmt~%") NIL)))
  )

(defun parse-elifstmt ()
  (parse-info (format NIL "Parsing elifstmt on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'if-st)
           (parse-expr)
           (parse-expr)
           (parse-expr))
          (T (parse-info "Unable to parse elifstmt~%") NIL)))
  )

(defun parse-exprs ()
  (parse-info (format NIL "Parsing exprs on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((parse-+exprs))
          ((parse-expr))
          (T (parse-info "Unable to parse exprs~%") NIL)))
  )

(defun parse-+exprs ()
  (parse-info (format NIL "Parsing +exprs on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((parse-expr)
           (parse-exprs))
          (T (parse-info "Unable to parse +exprs~%") NIL)))
  )

(defun parse-ids ()
  (parse-info (format NIL "Parsing ids on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'leftp-dt)
           (parse-id)
           (parse-prim)
           (expect 'rightp-dt))
          ((parse-+ids))
          (T (parse-info "Unable to parse ids~%") NIL)))
  )

(defun parse-+ids ()
  (parse-info (format NIL "Parsing +ids on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'leftp-dt)
           (parse-id)
           (parse-prim)
           (expect 'rightp-dt)
           (parse-ids))
          (T (parse-info "Unable to parse +ids~%") NIL)))
  )

(defun parse-const ()
  (parse-info (format NIL "Parsing const on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'boolean-ct))
          ((accept 'integer-ct))
          ((accept 'real-ct))
          ((accept 'string-ct))
          (T (parse-info "Unable to parse const~%") NIL)))
  )

(defun parse-id ()
  (parse-info (format NIL "Parsing id on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'function-it))
          ((accept 'variable-it))
          (T (parse-info "Unable to parse id~%") NIL)))
  )

(defun parse-prim ()
  (parse-info (format NIL "Parsing prim on ~S~%" *sym*))
  (let ((*depth* (+ *depth* 1)))
    (cond ((accept 'boolean-pt))
          ((accept 'integer-pt))
          ((accept 'real-pt))
          ((accept 'string-pt))
          (T (parse-info "Unable to parse prim~%") NIL)))
  )




(defun syntax-parse (symbol-table grammar depth)
  (let ((parse-tree (list (cons 'leftp-dt "("))))
    (do
      ((sym (table-pop symbol-table)
            (table-pop symbol-table)))
      ((null sym))
      (let ((token-type (car sym))
            (token      (cdr sym)))
        (cond ((equal token-type 'rightp-dt)   ;; Handle closing parenthesis specially
               (format T "~,,v,@A~%" (* 2 (- depth 1)) token)
               (return))
              ((equal token-type 'leftp-dt)   ;; Recurse on opening parenthesis
               (format T "~,,v,@A~%" (* 2 depth) token)
               (let ((subtree (syntax-parse symbol-table grammar (+ 1 depth))))
                 (setf parse-tree
                       (cons subtree parse-tree))))
              (T
                ;; Print to screen at correct indentation
                ;; See http://stackoverflow.com/questions/20072959/lisp-format-a-character-a-number-of-times
                (format T "~,,v,@A~%" (* 2 depth) token)
                (setf parse-tree
                      (cons sym parse-tree))
                ))))
    (setf parse-tree
          (cons (cons 'rightp-dt ")") parse-tree))
    (nreverse parse-tree)))
