(load "tokens")

(defparameter *oldsym* ())
(defparameter *sym* ())
(defparameter *symbol-table* ())
(defparameter *depth* 0)

(defun init-globals (symbol-table)
  (setf *oldsym* ()
        *sym* ()
        *symbol-table* symbol-table
        *depth* 0
        ))

;;; Convenience function so popping from symbol table fails gracefully.
(defun table-pop (symbol-table)
  (if (> (fill-pointer symbol-table) 0)
    (vector-pop symbol-table)
    (cons 'eof T)))

(defun get-sym ()
  (defparameter *oldsym* *sym*)
  (setf *sym* (table-pop *symbol-table*)))

(defun unget-sym ()
  (vector-push-extend *sym* *symbol-table*)
  (defparameter *sym* *oldsym*)
  *sym*)

(defun parse-reject (str)
  (format *enable-debug* "~,,v,@A" (* *depth* 2) (format NIL "[REJECT ~S] ~@?" *depth* str))
  ;(setf *accept* NIL)
  ;(unget-sym)
  ;(format *enable-debug* "~,,v,@A" (* *depth* 2) (format NIL "[REJECT ~S] *sym* reverted to ~S~%" *depth* *sym*))
  NIL)

(defun parse-info (str &optional (enable-indent T))
  (if enable-indent
    (format *enable-debug* "~,,v,@A" (* 2 *depth*) (format NIL "[INFO ~S] ~@?" *depth* str))
    (format *enable-debug* "~@?" str))
  )

(defun accept (token-type)
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Symbol to accept is ~S.. " *sym*))
    (cond ((equal (car *sym*) token-type)
           (parse-info (format NIL "accepting ~S. Next is ~S~%" token-type (get-sym)) NIL)
           T)
          (T
            (parse-info (format NIL "rejecting ~S~%" token-type) NIL)
            NIL)))
  )

(defun expect (token-type)
  (cond ((accept token-type) T)
        (T
          (parse-reject (format NIL "Expected ~S, got ~S instead~%" token-type (car *sym*))) NIL)))

(defun parse (symbol-table)
  (init-globals symbol-table)
  (get-sym)
  (parse-info (format NIL "Parsing on ~S~%" *sym*))
  (parse-S)
  (equal (car *sym*) 'eof))

(defun parse-S ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing S on ~S~%" *sym*))
    (cond ((parse-+S)
           (parse-info "Parsed: S -> +S~%") T)
          ((and (accept 'leftp-dt)
                (parse-S)
                (expect 'rightp-dt))
           (parse-info "Parsed: S -> ( S )~%") T)
          ((parse-expr)
           (parse-info "Parsed: S -> expr~%") T)
          ((parse-nil)
           (parse-info "Parsed: S -> nil~%") T)
          ((accept 'eof)
           (parse-info "Parsed: S -> $~%") T)
          (T
            ;(parse-info "Attempted all derivations, assuming empty string~%")
            (parse-reject "Unable to parse S~%")
            NIL))))

(defun parse-+S ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing S+ on ~S~%" *sym*))
    (cond ((and (accept 'leftp-dt)
                (parse-S)
                (expect 'rightp-dt)
                (parse-S))
           (parse-info "Parsed: S+ -> ( S ) S~%") T)
          ((and (parse-expr)
                (parse-S))
           (parse-info "Parsed: S+ -> expr S~%") T)
          ((and (parse-nil)
                (parse-S))
           (parse-info "Parsed: S+ -> nil S~%") T)
          (T
            ;(parse-info "Attempted all derivations, assuming empty string~%")
            (parse-reject "Unable to parse S+~%")
            NIL))))

(defun parse-expr ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing expr on ~S~%" *sym*))
    (cond ((parse-oper)
           (parse-info "Parsed: expr -> oper~%") T)
          ((parse-stmt)
           (parse-info "Parsed: expr -> stmt~%") T)
          (T (parse-reject "Unable to parse expr~%") NIL))))

(defun parse-nil ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing nil on ~S~%" *sym*))
    (cond ((and (accept 'leftp-dt)
                (expect 'rightp-dt))
           (parse-info "Parsed: nil -> ( )~%") T)
          (T (parse-reject "Unable to parse nil~%") NIL))))

(defun parse-oper ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing oper on ~S~%" *sym*))
    (cond ((and (accept 'leftp-dt)
                (parse-Poper)
                (expect 'rightp-dt))
           (parse-info "Parsed: oper -> ( Poper )~%") T)
          ((parse-const)
           (parse-info "Parsed: oper -> const~%") T)
          ((parse-id)
           (parse-info "Parsed: oper -> id~%") T)
          (T (parse-reject "Unable to parse oper~%") NIL))))

(defun parse-stmt ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing stmt on ~S~%" *sym*))
    (cond ((and (accept 'leftp-dt)
                (parse-Pstmt)
                (expect 'rightp-dt))
           (parse-info "Parsed: stmt -> ( Pstmt )~%") T)
          (T (parse-reject "Unable to parse stmt~%") NIL))))

(defun parse-Poper ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing Poper on ~S~%" *sym*))
    (cond ((and (accept 'assign-st)
                (parse-id)
                (parse-oper))
           (parse-info "Parsed: Poper -> := id oper~%") T)
          ((and (accept 'binop-ot)
                (parse-oper)
                (parse-oper))
           (parse-info "Parsed: Poper -> binop oper oper~%") T)
          ((and (accept 'unop-ot)
                (parse-oper))
           (parse-info "Parsed: Poper -> unop oper~%") T)
          (T (parse-reject "Unable to parse Poper~%") NIL))))

(defun parse-Pstmt ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing Pstmt on ~S~%" *sym*))
    (cond ((parse-ifstmt)
           (parse-info "Parsed: Pstmt -> ifstmt~%") T)
          ((parse-elifstmt)
           (parse-info "Parsed: Pstmt -> elifstmt~%") T)
          ;((and (accept 'if-st)
          ;      (parse-expr)
          ;      (parse-expr)
          ;      (or (parse-expr) T)))
          ((and (accept 'while-st)
                (parse-expr)
                (parse-exprs))
           (parse-info "Parsed: Pstmt -> while expr exprs~%") T)
          ((and (accept 'let-st)
                (expect 'leftp-dt)
                (parse-ids)
                (expect 'rightp-dt))
           (parse-info "Parsed: Pstmt -> let ( ids )~%") T)
          ((and (accept 'stdout-st)
                (parse-oper))
           (parse-info "Parsed: Pstmt -> stdout oper~%") T)
          (T (parse-reject "Unable to parse Pstmt~%") NIL))))

(defun parse-ifstmt ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing ifstmt on ~S~%" *sym*))
    (cond ((and (accept 'if-st)
                (parse-expr)
                (parse-expr))
           (parse-info "Parsed: ifstmt -> if expr expr~%") T)
          (T (parse-reject "Unable to parse ifstmt~%") NIL))))

(defun parse-elifstmt ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing elifstmt on ~S~%" *sym*))
    (cond ((and (accept 'if-st)
                (parse-expr)
                (parse-expr)
                (parse-expr))
           (parse-info "Parsed: elifstmt -> if expr expr expr~%") T)
          (T (parse-reject "Unable to parse elifstmt~%") NIL))))

(defun parse-exprs ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing exprs on ~S~%" *sym*))
    (cond ((parse-+exprs)
           (parse-info "Parsed: exprs -> +exprs~%") T)
          ((parse-expr)
           (parse-info "Parsed: exprs -> expr~%") T)
          (T (parse-reject "Unable to parse exprs~%") NIL))))

(defun parse-+exprs ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing +exprs on ~S~%" *sym*))
    (cond ((and (parse-expr)
                (parse-exprs))
           (parse-info "Parsed: +exprs -> expr exprs~%") T)
          (T (parse-reject "Unable to parse +exprs~%") NIL))))

(defun parse-ids ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing ids on ~S~%" *sym*))
    (cond ((parse-+ids)
           (parse-info "Parsed: ids -> +ids~%") T)
          ((and (accept 'leftp-dt)
                (parse-id)
                (parse-prim)
                (expect 'rightp-dt))
           (parse-info "Parsed: ids -> ( id prim )~%") T)
          (T (parse-reject "Unable to parse ids~%") NIL))))

(defun parse-+ids ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing +ids on ~S~%" *sym*))
    (cond ((and (accept 'leftp-dt)
                (parse-id)
                (parse-prim)
                (expect 'rightp-dt)
                (parse-ids))
           (parse-info "Parsed: +ids -> ( id prim ) ids~%") T)
          (T (parse-reject "Unable to parse +ids~%") NIL))))

(defun parse-const ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing const on ~S~%" *sym*))
    (cond ((accept 'boolean-ct)
           (parse-info "Parsed: const -> boolean-ct~%") T)
          ((accept 'integer-ct)
           (parse-info "Parsed: const -> integer-ct~%") T)
          ((accept 'real-ct)
           (parse-info "Parsed: const -> real-ct~%") T)
          ((accept 'string-ct)
           (parse-info "Parsed: const -> string-ct~%") T)
          (T (parse-reject "Unable to parse const~%") NIL))))

(defun parse-id ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing id on ~S~%" *sym*))
    (cond ((accept 'function-it)
           (parse-info "Parsed: id -> function-ct~%") T)
          ((accept 'variable-it)
           (parse-info "Parsed: id -> variable-ct~%") T)
          (T (parse-reject "Unable to parse id~%") NIL))))

(defun parse-prim ()
  (let ((*depth* (+ *depth* 1)))
    (parse-info (format NIL "Parsing prim on ~S~%" *sym*))
    (cond ((accept 'boolean-pt)
           (parse-info "Parsed: prim -> boolean-pt~%") T)
          ((accept 'integer-pt)
           (parse-info "Parsed: prim -> integer-pt~%") T)
          ((accept 'real-pt)
           (parse-info "Parsed: prim -> real-pt~%") T)
          ((accept 'string-pt)
           (parse-info "Parsed: prim -> string-pt~%") T)
          (T (parse-reject "Unable to parse prim~%") NIL))))




(defun syntax-parse (symbol-table grammar depth)
  (let ((parse-tree (list (cons 'leftp-dt "("))))
    (do
      ((sym (table-pop symbol-table)
            (table-pop symbol-table)))
      ((null sym))
      (let ((token-type (car sym))
            (token      (cdr sym)))
        (cond ((equal token-type 'rightp-dt)   ;; Handle closing parenthesis specially
               (format T "~,,v,@A~%" (* 2 (- depth 1)) token)
               (return))
              ((equal token-type 'leftp-dt)   ;; Recurse on opening parenthesis
               (format T "~,,v,@A~%" (* 2 depth) token)
               (let ((subtree (syntax-parse symbol-table grammar (+ 1 depth))))
                 (setf parse-tree
                       (cons subtree parse-tree))))
              (T
                ;; Print to screen at correct indentation
                ;; See http://stackoverflow.com/questions/20072959/lisp-format-a-character-a-number-of-times
                (format T "~,,v,@A~%" (* 2 depth) token)
                (setf parse-tree
                      (cons sym parse-tree))
                ))))
    (setf parse-tree
          (cons (cons 'rightp-dt ")") parse-tree))
    (nreverse parse-tree)))
